### ISSUE TITLE
ScanNet classification, can't obtain 9,305/2,606 training/testing instances

### ISSUE THREAD

**Issue by Yochengliu** [yangyanli/PointCNN#126]
How did you fix the benchmark files to reach 9,305/2,606 instances, as you mentioned in issue #29 ?

Can you update the benchmark files with the fixed files (maybe scannet-labels.combined.tsv and classes_ObjClassification-ShapeNetCore55.txt in ./data_conversions)? Thanks.

**Comment by MingChaoSun** [comment]
Hi,

I think the cannet-labels.combined.tsv and classes_ObjClassification-ShapeNetCore55.txt in ./data_conversions are fixed files.

Thanks,
Mingchao

**Comment by Yochengliu** [comment]
Really? But I extracted the instances exactly following your instructions, and nearly got the same instances as #29 , i.e., 7814/2169, rather than 9,305/2,606.

I have checked the scannet-labels.combined.tsv and classes_ObjClassification-ShapeNetCore55.txt carefully, and I found the label name problem seemed to be still exist. 

Is there anything I mistake? Thanks.

**Comment by MingChaoSun** [comment]
Sorry, I uploaded the wrong file before. T_T
I just updated the tsv file.

**Comment by Yochengliu** [comment]
Ok, I'll try it at once. Thank you very much!

**Comment by Yochengliu** [comment]
Using the updated tsv file, I get 9423/2634 instances rather than 9,305/2,606. It seems that there is something wrong, or are 9423/2634 instances also okay? Could you please have a check? Thanks.

**Comment by MingChaoSun** [comment]
This tsv file has been modified several times， so there is a small gap from the version one year ago. Compared with the original version, it should have corrected more label errors，therefore， a little more instances is reasonable.

**Comment by Yochengliu** [comment]
Ok, I get it. Thank you very much.
